//2,3,4,6 - Inches
//11, 33 - Gallons
// Plants that have gallon sizes are "Gold Dust" - 3 gallon, "Warneckii" - 3 gallon, "Marginata" - 3 gallon, "Sansevieria" - 1 gallon, "Magnificent" - 1 gallon, "Song of Jamaica" - 1 gallon, "Trinette green" - 1 and 3 gallon, 
// Quantity is total quantity regardless of size

const products = [
  { id: 1, name: "Janet Craig Compacta", size: [4, 6], quantity: 150, price: 15, description: "", review: "4.5/5" },
  { id: 2, name: "Petra", size: [3, 4, 6], quantity: 3050, price: 20, description: "", review: "4.2/5" },
  { id: 3, name: "Mamey", size: [4], quantity: 700, price: 18, description: "", review: "4.3/5" },
  { id: 4, name: "Banana", size: [4, 6], quantity: 150, price: 17, description: "Available in Red or Yellow.", review: "4.0/5" },
  { id: 5, name: "Red Bartik", size: [4], quantity: 50, price: 16, description: "", review: "4.6/5" },
  { id: 6, name: "Gold Dust", size: [3, 4, 6], quantity: 645, price: 12, description: "", review: "4.3/5" },
  { id: 7, name: "Song Of India", size: [], quantity: 0, price: 18, description: "", review: "4.2/5" },
  { id: 8, name: "Warneckii", size: [2, 4], quantity: 150, price: 15, description: "Available in Lemon Lime or Green.", review: "4.4/5" },
  { id: 9, name: "Croton", size: [2, 3, 4], quantity: 890, price: 19, description: "Available in Sunny Star, Gold Star, or Fantasy.", review: "4.3/5" },
  { id: 10, name: "Gold Sandriana", size: [4], quantity: 100, price: 14, description: "", review: "4.1/5" },
  { id: 11, name: "Marginata", size: [2, 3, 4, 6], quantity: 710, price: 10, description: "Available in Bicolor or Magenta.", review: "4.5/5" },
  { id: 12, name: "Pothos", size: [2, 3, 4, 6], quantity: 1150, price: 0, description: "Available in Golden, Neon, Jade, N'joy, Pearl & Jade, Brazilian, or Hawaiian.", review: "0/5" },
  { id: 13, name: "Tradescantia Zebrina Purple", size: [2, 3, 4], quantity: 1200, price: 8, description: "", review: "4.4/5" },
  { id: 14, name: "Sansevieria", size: [2, 3, 4, 6], quantity: 2600, price: 9, description: "Available in 1PP or 2PP and Superba, Moonshine, Black Coral, Laurentii, Zeylanica, or Robusta.", review: "4.3/5" },
  { id: 15, name: "Fittonia", size: [2, 3, 4], quantity: 300, price: 12, description: "Available in White or Pink & Red.", review: "4.5/5" },
  { id: 16, name: "Peperomia", size: [2, 3, 4, 6], quantity: 2843, price: 14, description: "Available in Green, Marble, Ginny, Variegated, Red Margin, Little Toscani, Frost, or Rosso.", review: "4.6/5" },
  { id: 17, name: "Maranta", size: [2, 3, 4], quantity: 1700, price: 20, description: "Available in Red, Green, Lemon Lime, Amagaris, or Beauty Kim.", review: "4.3/5" },
  { id: 18, name: "Florida Beauty", size: [2, 3, 4, 6], quantity: 606, price: 11, description: "", review: "4.2/5" },
  { id: 19, name: "Sloppy Painter", size: [], quantity: 0, price: 11, description: "", review: "4.2/5" },
  { id: 20, name: "Roheo", size: [2, 3, 4, 6], quantity: 530, price: 11, description: "Available in Tricolor or Bicolor.", review: "4.2/5" },
  { id: 21, name: "Trinette green", size: [4, 6], quantity: 105, price: 11, description: "Available in Tricolor or Bicolor.", review: "4.2/5" },
  { id: 22, name: "Aloe Vera", size: [3, 4, 6], quantity: 800, price: 10, description: "", review: "4.8/5" },
  { id: 23, name: "Ivy", size: [2, 4, 6], quantity: 910, price: 9, description: "Available in Glacier, Marengo, or English.", review: "4.1/5" },
  { id: 24, name: "Mrs. Icetone", size: [], quantity: 0, price: 13, description: "", review: "4.0/5" },
  { id: 25, name: "Magnificent", size: [4, 6], quantity: 519, price: 21, description: "", review: "4.5/5" },
  { id: 26, name: "Song of Jamaica", size: [4, 6], quantity: 570, price: 16, description: "", review: "4.4/5" },
  { id: 27, name: "Excellent", size: [], quantity: 0, price: 10, description: "", review: "4.4/5" },
  { id: 28, name: "Spider Plant", size: [2, 3, 4], quantity: 1300, price: 12, description: "", review: "4.5/5" },
  { id: 29, name: "Aurora of Siam", size: [4], quantity: 10, price: 20, description: "", review: "4.6/5" },
  { id: 30, name: "Assorted Succulents", size: [2, 3, 4], quantity: 700, price: 8, description: "", review: "4.7/5" },
  { id: 31, name: "Assorted Echeveria", size: [2, 3, 4], quantity: 900, price: 10, description: "", review: "4.6/5" },
  { id: 32, name: "Assorted Crassula", size: [2, 3, 4], quantity: 900, price: 9, description: "", review: "4.5/5" },
  { id: 33, name: "Jade", size: [2, 3, 4], quantity: 900, price: 14, description: "", review: "4.4/5" },
  { id: 34, name: "Crasula", size: [2, 3, 4], quantity: 900, price: 14, description: "", review: "4.4/5" },
  { id: 35, name: "Cactus", size: [3, 4], quantity: 850, price: 15, description: "", review: "4.6/5" },
  { id: 36, name: "Succulent", size: [3, 4], quantity: 200, price: 0, description: "", review: "0/5" },
  { id: 37, name: "Echeveria", size: [3, 4], quantity: 200, price: 0, description: "", review: "0/5" },
  { id: 38, name: "Liriope Aztec", size: [4], quantity: 100, price: 12, description: "", review: "4.1/5" },
  { id: 39, name: "Dieffenbachia Camille", size: [], quantity: 0, price: 20, description: "", review: "4.2/5" },
  { id: 40, name: "Assorted Crotons in a pot", size: [4], quantity: 0, price: 0, description: "", review: "0/5" },
  { id: 41, name: "Assorted Dracaena in a pot", size: [4], quantity: 0, price: 0, description: "", review: "0/5" },
  { id: 42, name: "Assorted Sansevieria in a pot", size: [4], quantity: 0, price: 0, description: "", review: "0/5" },
  { id: 43, name: "Assorted Peperomia in a pot", size: [4], quantity: 0, price: 0, description: "", review: "0/5" },
  { id: 44, name: "Assorted Ivy", size: [2, 3, 4], quantity: 1200, price: 0, description: "", review: "0/5" },
  { id: 45, name: "Hypoestes mix/red/pink/white", size: [2, 3, 4], quantity: 1300, price: 0, description: "", review: "0/5" },
  { id: 46, name: "Coffee Plant", size: [2, 3, 4], quantity: 200, price: 14, description: "", review: "4.5/5" },
  { id: 47, name: "China Doll", size: [2, 3, 4], quantity: 200, price: 10, description: "", review: "4.4/5" },
  { id: 48, name: "Asparagus Sprengeri", size: [], quantity: 0, price: 9, description: "", review: "4.6/5" },
  { id: 49, name: "Schefflera Arboricola mini", size: [4, 6], quantity: 300, price: 0, description: "", review: "0/5" },
  { id: 50, name: "Neanthebella Palm", size: [3], quantity: 200, price: 0, description: "", review: "0/5" },
  { id: 51, name: "Alocasia", size: [4], quantity: 120, price: 0, description: "", review: "0/5" },
  { id: 52, name: "Ficus elastica Burgundy", size: [4], quantity: 60, price: 0, description: "", review: "0/5" },
  { id: 53, name: "Ctenanthe Oppenhimiana", size: [4], quantity: 100, price: 0, description: "", review: "0/5" },
  { id: 54, name: "Philo", size: [3, 4], quantity: 274, price: 0, description: "", review: "0/5" },
  { id: 55, name: "Pilea Peperomioides", size: [3], quantity: 100, price: 0, description: "", review: "0/5" },
  { id: 56, name: "Flax Lily", size: [4], quantity: 1000, price: 0, description: "", review: "0/5" },
  { id: 57, name: "Staghorn Fern", size: [3], quantity: 100, price: 0, description: "", review: "0/5" },
  { id: 58, name: "Button Fern", size: [3], quantity: 100, price: 0, description: "", review: "0/5" },
  { id: 59, name: "Xanthosoma Lindenii", size: [3], quantity: 100, price: 0, description: "", review: "0/5" },
  { id: 60, name: "Monstera Deliciosa", size: [2], quantity: 150, price: 0, description: "", review: "0/5" },
];

export default products;
