const products = [
    {
      id: 1,
      name: "JANET CRAIG COMPACTA",
      description: "The Janet Craig Compacta is a popular indoor plant known for its deep green, glossy leaves. It thrives in low to medium light and requires minimal watering, making it an excellent choice for beginners.",
      price: 29.99,
      quantity: 10,
      review: 4.5,
    },
    {
      id: 2,
      name: "PETRA, MAMMEY",
      description: "The Petra, also known as Croton, is a vibrant houseplant with multicolored leaves featuring shades of yellow, red, and green. It prefers bright indirect light and regular watering to keep its soil moist but not waterlogged.",
      price: 49.99,
      quantity: 5,
      review: 4.0,
    },
    {
      id: 3,
      name: "YELLOW & RED BANANA RED BATIK, GOLD DUST",
      description: "The Yellow & Red Banana, also known as Musa, is a striking plant with large, colorful leaves. It thrives in bright indirect light and requires regular watering to maintain its lush appearance.",
      price: 13.99,
      quantity: 7,
      review: 4.9,
    },
    {
      id: 4,
      name: "SONG OF INDIA",
      description: "The Song of India, or Dracaena Reflexa, is an attractive plant with narrow, green leaves edged in yellow. It does well in bright, indirect light and needs to be watered when the top inch of soil is dry.",
      price: 17.99,
      quantity: 20,
      review: 3.8,
    },
    {
      id: 5,
      name: "GREEN & LEMON LIME WARNECKII",
      description: "The Green & Lemon Lime Warneckii, also known as Dracaena Warneckii, features striking striped leaves in shades of green and lemon. It prefers bright, indirect light and should be watered when the top inch of soil dries out.",
      price: 21.99,
      quantity: 12,
      review: 4.7,
    },
    {
      id: 6,
      name: "GOLD SANDRIANA",
      description: "The Gold Sandriana, or Dracaena Fragrans, is a popular indoor plant with bright green leaves edged in gold. It thrives in low to bright indirect light and needs to be watered when the top inch of soil is dry.",
      price: 27.99,
      quantity: 30,
      review: 4.2,
    },
    {
      id: 7,
      name: "BICOLOR/MAGENTA MARGI",
      description: "The Bicolor/Magenta Margi, or Cordyline, features striking leaves with shades of green, pink, and magenta. It prefers bright, indirect light and should be watered when the top inch of soil is dry.",
      price: 27.99,
      quantity: 30,
      review: 4.2,
    },
    {
      id: 8,
      name: "TRADESCANTIA ZEBRINA PU",
      description: "The Tradescantia Zebrina, also known as Wandering Jew, is a fast-growing plant with purple and silver striped leaves. It thrives in bright, indirect light and needs regular watering to keep the soil moist.",
      price: 27.99,
      quantity: 30,
      review: 4.2,
    },
    {
      id: 9,
      name: "SANSEVERIA SUPURBA ONE",
      description: "The Sansevieria Supurba, or Snake Plant, is a hardy plant with tall, upright leaves that are green with white edges. It does well in low to bright light and requires infrequent watering, making it very low-maintenance.",
      price: 27.99,
      quantity: 30,
      review: 4.2,
    },
    {
      id: 10,
      name: "SANSEVERIA SUPURBA, LAURENTII AND ROBUST",
      description: "The Sansevieria Laurentii, also known as the Snake Plant, has tall, sword-like leaves with green centers and yellow edges. It thrives in low to bright light and needs infrequent watering, making it ideal for busy households.",
      price: 27.99,
      quantity: 30,
      review: 4.2,
    },
    {
      id: 11,
      name: "PEP GREEN/ MARBLE/JENN",
      description: "The Pep Green Marble plant is a stunning addition to any space, featuring marbled green leaves with a glossy finish. This plant thrives in medium to bright indirect light and enjoys high humidity levels.",
      price: 19.99,
      quantity: 15,
      review: 4.3,
    },
    {
      id: 12,
      name: "MARANTA RED, GREEN LEMON LIME",
      description: "Maranta Red and Green Lemon Lime plants are known for their striking variegated leaves that display a beautiful mix of red, green, and lemon lime colors. These plants prefer bright indirect light and high humidity.",
      price: 22.99,
      quantity: 18,
      review: 4.6,
    },
    {
      id: 13,
      name: "FLORIDA BEAUTY",
      description: "The Florida Beauty plant features speckled green and yellow leaves that add a tropical flair to any room. This plant thrives in bright, indirect light and requires regular watering to keep the soil moist.",
      price: 24.99,
      quantity: 12,
      review: 4.4,
    },
    {
      id: 14,
      name: "SLOPPY PAINTER",
      description: "The Sloppy Painter plant boasts uniquely patterned leaves that look as if they've been splattered with paint. This plant does well in low to medium indirect light and prefers its soil to dry out between waterings.",
      price: 14.99,
      quantity: 25,
      review: 4.1,
    },
    {
      id: 15,
      name: "ROHEO TRICOLOR",
      description: "The Roheo Tricolor plant features vibrant leaves with shades of green, pink, and purple, making it a colorful addition to any space. It prefers bright indirect light and moderate watering.",
      price: 26.99,
      quantity: 8,
      review: 4.7,
    },
    {
      id: 16,
      name: "TRINETTE",
      description: "The Trinette plant is known for its beautiful variegated leaves that showcase a blend of green and creamy white. This plant thrives in bright indirect light and requires regular watering to keep the soil moist.",
      price: 23.99,
      quantity: 10,
      review: 4.5,
    },
    {
      id: 17,
      name: "ALOE VERA",
      description: "Aloe Vera is a popular succulent known for its medicinal properties and thick, fleshy leaves. It thrives in bright indirect light and requires infrequent watering, making it a low-maintenance plant.",
      price: 9.99,
      quantity: 30,
      review: 4.8,
    },
    {
      id: 18,
      name: "IVY GLACIER/MARENGO",
      description: "The Ivy Glacier Marengo plant features delicate ivy leaves with a beautiful blend of green and white variegation. It does well in bright indirect light and requires regular watering to keep the soil evenly moist.",
      price: 16.99,
      quantity: 20,
      review: 4.2,
    },
    {
      id: 19,
      name: "MRS ICETONE",
      description: "Mrs. Icetone is a striking plant with frosty green leaves that have a cool, icy appearance. This plant thrives in bright indirect light and prefers to have its soil kept moist but not soggy.",
      price: 20.99,
      quantity: 12,
      review: 4.3,
    },
    {
      id: 20,
      name: "MAGNIFICIENT",
      description: "The Magnificent plant lives up to its name with large, bold leaves that make a statement in any space. It prefers bright indirect light and regular watering to maintain its lush appearance.",
      price: 29.99,
      quantity: 5,
      review: 4.9,
    },
  ];
  export default products;