const products = [
  { id: 1, name: "Janet Craig Compacta", size: [4, 6], quantity: 1100, price: 15, description: "Compact indoor plant.", review: "4.5/5" },
  { id: 2, name: "Petra", size: [2, 3, 4, 6], quantity: 4650, price: 20, description: "Vibrant croton variety.", review: "4.2/5" },
  { id: 3, name: "Mammey/Red Batik", size: [2, 3, 4, 6], quantity: 5150, price: 18, description: "Tropical plant variety.", review: "4.3/5" },
  { id: 4, name: "Gold Dust", size: [2, 3, 4, 6], quantity: 2250, price: 17, description: "Speckled golden leaves.", review: "4.0/5" },
  { id: 5, name: "Song of India", size: [4, 6], quantity: 380, price: 16, description: "Variegated tropical plant.", review: "4.6/5" },
  { id: 6, name: "Green / Lemon Lime Warneckii", size: [4, 6], quantity: 1650, price: 12, description: "Hardy green foliage.", review: "4.3/5" },
  { id: 7, name: "Croton Sunny Star", size: [2, 3, 4, 6], quantity: 1350, price: 18, description: "Bright green and yellow.", review: "4.2/5" },
  { id: 8, name: "Gold Sandriana", size: [4, 6], quantity: 2400, price: 15, description: "Golden striped leaves.", review: "4.4/5" },
  { id: 9, name: "Bicolor/Magenta Marginata", size: [2, 3, 4, 6], quantity: 2770, price: 19, description: "Two-toned margins.", review: "4.3/5" },
  { id: 10, name: "Silver Satin Golden Pothos", size: [2, 3, 4, 6], quantity: 330, price: 14, description: "Silvery patterned leaves.", review: "4.1/5" },
  { id: 11, name: "Tradescantia Zebrina Purple", size: [2, 3, 4, 6], quantity: 750, price: 10, description: "Striped purple and green.", review: "4.5/5" },
  { id: 12, name: "Sansevieria Superba", size: [2, 3, 4, 6], quantity: 2250, price: 18, description: "Classic snake plant.", review: "4.7/5" },
  { id: 13, name: "Fittonia White", size: [2, 3, 4], quantity: 400, price: 8, description: "White-veined plant.", review: "4.4/5" },
  { id: 14, name: "Fittonia Pink", size: [2, 3, 4], quantity: 100, price: 9, description: "Pink-veined plant.", review: "4.3/5" },
  { id: 15, name: "Peperomia", size: [2, 3, 4, 6], quantity: 3650, price: 12, description: "Compact green foliage", review: "4.5/5" },
  { id: 16, name: "Red Maranta", size: [4, 6], quantity: 2200, price: 14, description: "Prayer plant variety.", review: "4.6/5" },
  { id: 17, name: "Florida Beauty", size: [2, 3, 4, 6], quantity: 250, price: 20, description: "Bright and vibrant plant.", review: "4.3/5" },
  { id: 18, name: "Rhoeo Tricolor", size: [2, 3, 4, 6], quantity: 1610, price: 11, description: "Three-colored leaves.", review: "4.2/5" },
  { id: 19, name: "Aloe Vera", size: [4, 6], quantity: 750, price: 10, description: "Medicinal succulent.", review: "4.8/5" },
  { id: 20, name: "Ivy Glacier", size: [2, 3, 4, 6], quantity: 1300, price: 9, description: "Frosty foliage.", review: "4.1/5" },
  { id: 21, name: "Mrs. Icetone", size: [4, 6], quantity: 110, price: 13, description: "Unique foliage design.", review: "4.0/5" },
  { id: 22, name: "Magnificent", size: [6], quantity: 20, price: 21, description: "Broad vibrant leaves.", review: "4.5/5" },
  { id: 23, name: "Song of Jamaica", size: [4, 6], quantity: 550, price: 16, description: "Exotic plant variety.", review: "4.4/5" },
  { id: 24, name: "Spider Plant", size: [2, 3, 4], quantity: 670, price: 12, description: "Easy care foliage.", review: "4.5/5" },
  { id: 25, name: "Aurora of Siam", size: [4], quantity: 420, price: 20, description: "Ornamental plant.", review: "4.6/5" },
  { id: 26, name: "Succulents", size: [2, 3, 4], quantity: 1100, price: 8, description: "Mixed succulents.", review: "4.7/5" },
  { id: 27, name: "Echeveria", size: [2, 3, 4], quantity: 1100, price: 10, description: "Colorful rosettes.", review: "4.6/5" },
  { id: 28, name: "Crassula", size: [2, 3, 4], quantity: 1100, price: 9, description: "Mix of Crassula plants.", review: "4.5/5" },
  { id: 29, name: "Jade Plant", size: [2, 3, 4], quantity: 900, price: 14, description: "Popular indoor succulent.", review: "4.4/5" },
  { id: 30, name: "Cactus", size: [3, 4], quantity: 1100, price: 15, description: "Low-maintenance cactus.", review: "4.6/5" },
  { id: 31, name: "Croton Gold Star", size: [2, 3, 4, 6], quantity: 1200, price: 17, description: "Bright gold and green.", review: "4.3/5" },
  { id: 32, name: "Liriope Aztec", size: [4], quantity: 500, price: 12, description: "Grass-like foliage.", review: "4.1/5" },
  { id: 33, name: "Dieffenbachia Camille", size: [3, 4], quantity: 100, price: 20, description: "Assorted colorful crotons.", review: "4.2/5" },
  { id: 34, name: "Hypoestes Mix", size: [2, 3, 4], quantity: 150, price: 8, description: "Polka dot plant mix.", review: "4.0/5" },
  { id: 35, name: "Coffee Plant", size: [2, 3, 4], quantity: 150, price: 14, description: "Grow your own coffee!", review: "4.5/5" },
  { id: 36, name: "China Doll", size: [2, 3, 4], quantity: 150, price: 10, description: "Delicate indoor foliage.", review: "4.4/5" },
  { id: 37, name: "Asparagus Sprengeri", size: [2, 3, 4], quantity: 150, price: 9, description: "Soft feathery foliage.", review: "4.6/5" },
  { id: 38, name: "Aralia Fruticosa", size: [2], quantity: 50, price: 13, description: "Unique textured leaves.", review: "4.2/5" },
  { id: 39, name: "Schefflera Arboricola Mini", size: [4], quantity: 200, price: 16, description: "Compact umbrella plant.", review: "4.5/5" },
];

export default products;
